#!/bin/bash  

repHeader="xuxinlai2002"
imgs=("btcorg" "btchardfork" "btcnew")
ctns=("1" "2")
declare ctnNum=0

#test instruction
logInfo="getinfo : get blocks info from all  nodes "
echo $logInfo | tee tests/log/$1.log

for img in "${imgs[@]}"
do
  for ctn in "${ctns[@]}"
  do	
	logInfo="nodes: ${img}Node$ctn info"
 	echo $logInfo | tee -a tests/log/$1.log
	
	docker exec -it ${img}Node$ctn bitcoin-cli -regtest getinfo > temp.con
        docker exec -it ${img}Node$ctn bitcoin-cli -regtest getaddressesbyaccount "" >temp2.con	
        cat -v temp.con |tr -d "^M" |tee -a tee tests/log/$1.log

        logInfo="nodes: ${img}Node$ctn addresses"
        echo $logInfo | tee -a tests/getinfo.log

        cat -v temp2.con |tr -d "^M" |tee -a tee tests/log/$1.log
  done
done
